main: com.winthier.wall.WallPlugin
name: Wall

version: 0.1
api-version: '1.20'

description: Display walls of text to players
author: StarTux
website: https://cavetale.com

depend: [Core]
softdepend: [Mytems]

commands:

  wall:
    description: Display a wall of text
    usage: /<command> <page>
    permission: wall.wall

  discord:
    description: Discord link
    usage: /discord
    permission: wall.discord

permissions:

  wall.wall:
    description: Use the /wall command
    default: op

  wall.admin:
    description: Use admin commands
    default: op

  wall.discord:
    description: Use /discord
    default: op