name: Wall
description: Display walls of text to players
author: StarTux
version: 0.1
api-version: 1.13
website: https://cavetale.com
main: com.winthier.wall.WallPlugin
depend: [Core]
softdepend: [Mytems]
commands:
  wall:
    description: Display a wall of text
    usage: /<command> <page>
    permission: wall.wall
permissions:
  wall.wall:
    description: Use the /wall command
    default: op
  wall.admin:
    description: Use admin commands
    default: op
